# Generated by Django 5.2.6 on 2025-09-23 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('tops_and_tshirts', 'Tops and T-Shirts'), ('polo_and_shirts', 'Polo and Shirts'), ('jerseys', 'Jerseys'), ('shorts', 'Shorts'), ('pants_and_leggings', 'Pants and Leggings'), ('hoodies_and_sweatshirts', 'Hoodies and Sweatshirts'), ('jacket_and_tracktops', 'Jacket and Tracktops')], default='update', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
