# Generated by Django 5.2.6 on 2025-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tops_and_tshirts', 'Tops and T-Shirts'), ('polo_and_shirts', 'Polo and Shirts'), ('jerseys', 'Jerseys'), ('shorts', 'Shorts'), ('pants_and_leggings', 'Pants and Leggings'), ('hoodies_and_sweatshirts', 'Hoodies and Sweatshirts'), ('jacket_and_tracktops', 'Jacket and Tracktops')], default='update', max_length=50),
        ),
    ]
