# Generated by Django 5.2.6 on 2025-09-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_views',
            field=models.IntegerField(default=0),
        ),
    ]
